/**
 * API 回應錯誤碼（單一真相）。
 *
 * domain exception 的 `code` 一律引用此處，避免 SCREAMING_SNAKE 字面值散落各檔；
 * 前端 / 測試需要對特定錯誤做分支時，也 import 此常數比對，不要硬寫字串。
 */
export const ResponseCodes = {
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_LOCKED: 'ACCOUNT_NOT_LOCKED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  CANNOT_DELETE_SELF: 'CANNOT_DELETE_SELF',
  CANNOT_DISABLE_SELF: 'CANNOT_DISABLE_SELF',
  DEFAULT_MEMBER_NOT_DELETABLE: 'DEFAULT_MEMBER_NOT_DELETABLE',
  DEFAULT_MEMBER_NOT_EDITABLE: 'DEFAULT_MEMBER_NOT_EDITABLE',
  DUPLICATE_ROLE_NAME: 'DUPLICATE_ROLE_NAME',
  DEFAULT_ROLE_NOT_DELETABLE: 'DEFAULT_ROLE_NOT_DELETABLE',
  DEFAULT_ROLE_NOT_EDITABLE: 'DEFAULT_ROLE_NOT_EDITABLE',
  DEFAULT_ROLE_NOT_FOUND: 'DEFAULT_ROLE_NOT_FOUND',
  ROLE_HAS_MEMBERS: 'ROLE_HAS_MEMBERS',
  INVALID_PERMISSION_CODE: 'INVALID_PERMISSION_CODE',
  INVALID_PERMISSION_COMBINATION: 'INVALID_PERMISSION_COMBINATION',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  IP_LIST_NOT_FOUND: 'IP_LIST_NOT_FOUND',
  INVALID_MEMBER_ID: 'INVALID_MEMBER_ID',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  INVALID_MEMBER_NAME: 'INVALID_MEMBER_NAME',
  INVALID_UPLOAD: 'INVALID_UPLOAD',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_FORBIDDEN: 'ATTACHMENT_FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ResponseCode = (typeof ResponseCodes)[keyof typeof ResponseCodes];
